// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyFirstBlazorApp.Data.Modals;

#nullable disable

namespace MyFirstBlazorApp.Migrations
{
    [DbContext(typeof(EmployeeManagerDbContext))]
    [Migration("20231016023343_AddMoreEmployees")]
    partial class AddMoreEmployees
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyFirstBlazorApp.Data.Modals.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sales"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Human Resources"
                        },
                        new
                        {
                            Id = 5,
                            Name = "IT"
                        });
                });

            modelBuilder.Entity("MyFirstBlazorApp.Data.Modals.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DepartmentId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeveloper")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 2,
                            FirstName = "Dusty",
                            IsDeveloper = false,
                            LastName = "Shaw"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            FirstName = "Enoch",
                            IsDeveloper = false,
                            LastName = "Whitaker"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 4,
                            FirstName = "Garion",
                            IsDeveloper = true,
                            LastName = "Cox"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 5,
                            FirstName = "Jack",
                            IsDeveloper = true,
                            LastName = "Beans"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 2,
                            FirstName = "Jill",
                            IsDeveloper = false,
                            LastName = "Hill"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 1,
                            FirstName = "Jane",
                            IsDeveloper = false,
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 4,
                            FirstName = "Joe",
                            IsDeveloper = false,
                            LastName = "Pickle"
                        });
                });

            modelBuilder.Entity("MyFirstBlazorApp.Data.Modals.Employee", b =>
                {
                    b.HasOne("MyFirstBlazorApp.Data.Modals.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("MyFirstBlazorApp.Data.Modals.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
